language: go

sudo: required
dist: trusty

go:
 - 1.6

install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx
  - sudo ./scripts/travis-install-rkt.sh
  - sudo apt-get install -qq bats

script:
  - ./build.sh
  - sudo PATH=${GOPATH}/bin:$PATH ./tests.sh
  - sudo PATH=${GOPATH}/bin:$PATH ./examples/build.sh
